services:
  laravel-app:
      build:
        context: ../backend           # Laravel ソースがあるディレクトリ
        dockerfile: ../docker/dockerfile.backend.dev
      image: buildsuite-backend:dev
      container_name: buildsuite-backend-container
      env_file:
        - ../backend/.env # Laravelの.envファイルを指定
      environment:
          - APP_ENV=local
          - APP_DEBUG=true
      networks:
          - buildsuite-network  # 追加: Nginxと通信できるようにする
      volumes:
      - ../backend:/var/www/html  # 開発環境ではソースコード全体をマウント
      expose:
        - "9000"
      depends_on:
          - redis
          - meilisearch
      healthcheck:
          test: ["CMD", "php-fpm", "-t"]
          interval: 30s
          timeout: 10s
          retries: 3

      # command: bash -c "php artisan migrate --force && php-fpm"
      # ★環境に応じてユーザ指定（www-data:www-data）を変更すること★
      command: bash -c "
        chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
        chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
        if php artisan migrate:status | grep -q 'No'; then
          echo 'Running migrations';
          php artisan migrate --force;
        else
          echo 'Migrations already up to date';
        fi &&
        php-fpm"

  nginx:
    image: nginx:alpine
    container_name: buildsuite-nginx-container
    ports:
        - "8080:80"
    volumes:
        - ../backend:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - buildsuite-network
    depends_on:
        - laravel-app


  redis:
      image: 'redis:alpine'
      ports:
          - '6379:6379'
      volumes:
          - 'sail-redis:/data'
      networks:
          - buildsuite-network
      healthcheck:
          test:
              - CMD
              - redis-cli
              - ping
          retries: 3
          timeout: 5s

  meilisearch:
      image: 'getmeili/meilisearch:latest'
      ports:
          - '7700:7700'
      environment:
          MEILI_NO_ANALYTICS: 'false'
      volumes:
          - 'sail-meilisearch:/meili_data'
      networks:
          - buildsuite-network
      healthcheck:
          test:
              - CMD
              - wget
              - '--no-verbose'
              - '--spider'
              - 'http://127.0.0.1:7700/health'
          retries: 3
          timeout: 5s


volumes:
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local


networks:
  buildsuite-network:
    external: true
