<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Partner;
use App\Models\User;

class PartnersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 既存のパートナーデータをクリア
        Partner::truncate();

        // テスト用ユーザーを取得（存在しない場合は作成）
        $user = User::first();
        if (!$user) {
            $user = User::create([
                'login_id' => 'test001',
                'employee_id' => 1, // 既存のemployee_idを参照
                'password' => bcrypt('password'),
                'system_level' => 'staff',
                'is_active' => true,
            ]);
        }

        // 取引先データ
        $partners = [
            [
                'partner_code' => 'CUST001',
                'partner_name' => '株式会社サンプル建設',
                'partner_name_print' => '株式会社サンプル建設',
                'partner_name_kana' => 'カブシキガイシャサンプルケンセツ',
                'partner_type' => 'customer',
                'representative' => '田中太郎',
                'representative_kana' => 'タナカタロウ',
                'branch_name' => '本社',
                'postal_code' => '100-0001',
                'address' => '東京都千代田区千代田1-1-1',
                'building_name' => 'サンプルビル1F',
                'phone' => '03-1234-5678',
                'fax' => '03-1234-5679',
                'email' => 'info@sample-construction.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 100.00,
                'bill_allocation' => 0.00,
                'establishment_date' => '1990-01-01',
                'capital_stock' => 10000,
                'previous_sales' => 500000,
                'employee_count' => 50,
                'business_description' => '建設業',
                'bank_name' => 'サンプル銀行',
                'branch_name_bank' => '本店',
                'account_type' => 'current',
                'account_number' => '1234567',
                'account_holder' => '株式会社サンプル建設',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            [
                'partner_code' => 'SUPP001',
                'partner_name' => '株式会社サンプル建材',
                'partner_name_print' => '株式会社サンプル建材',
                'partner_name_kana' => 'カブシキガイシャサンプルケンザイ',
                'partner_type' => 'supplier',
                'representative' => '佐藤次郎',
                'representative_kana' => 'サトウジロウ',
                'branch_name' => '本社',
                'postal_code' => '200-0001',
                'address' => '東京都中央区中央1-1-1',
                'building_name' => '建材ビル2F',
                'phone' => '03-2345-6789',
                'fax' => '03-2345-6790',
                'email' => 'info@sample-materials.co.jp',
                'is_subcontractor' => true,
                'payment_date' => 99,
                'payment_method' => '振込',
                'payment_cash_allocation' => 80.00,
                'payment_bill_allocation' => 20.00,
                'establishment_date' => '1985-01-01',
                'capital_stock' => 5000,
                'previous_sales' => 200000,
                'employee_count' => 30,
                'business_description' => '建材販売',
                'bank_name' => '建材銀行',
                'branch_name_bank' => '本店',
                'account_type' => 'current',
                'account_number' => '7654321',
                'account_holder' => '株式会社サンプル建材',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            [
                'partner_code' => 'BOTH001',
                'partner_name' => '株式会社サンプル総合',
                'partner_name_print' => '株式会社サンプル総合',
                'partner_name_kana' => 'カブシキガイシャサンプルソウゴウ',
                'partner_type' => 'both',
                'representative' => '山田三郎',
                'representative_kana' => 'ヤマダサブロウ',
                'branch_name' => '本社',
                'postal_code' => '300-0001',
                'address' => '東京都港区港1-1-1',
                'building_name' => '総合ビル3F',
                'phone' => '03-3456-7890',
                'fax' => '03-3456-7891',
                'email' => 'info@sample-general.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 90.00,
                'bill_allocation' => 10.00,
                'payment_date' => 99,
                'payment_method' => '振込',
                'payment_cash_allocation' => 70.00,
                'payment_bill_allocation' => 30.00,
                'establishment_date' => '1980-01-01',
                'capital_stock' => 15000,
                'previous_sales' => 800000,
                'employee_count' => 100,
                'business_description' => '総合建設業',
                'bank_name' => '総合銀行',
                'branch_name_bank' => '本店',
                'account_type' => 'current',
                'account_number' => '1111111',
                'account_holder' => '株式会社サンプル総合',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            // 見積用の顧客データを追加
            [
                'partner_code' => 'CUST002',
                'partner_name' => '株式会社東京住宅',
                'partner_name_print' => '株式会社東京住宅',
                'partner_name_kana' => 'カブシキガイシャトウキョウジュウタク',
                'partner_type' => 'customer',
                'representative' => '鈴木一郎',
                'representative_kana' => 'スズキイチロウ',
                'branch_name' => '本社',
                'postal_code' => '150-0001',
                'address' => '東京都渋谷区渋谷1-1-1',
                'building_name' => '東京住宅ビル5F',
                'phone' => '03-4567-8901',
                'fax' => '03-4567-8902',
                'email' => 'info@tokyo-housing.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 100.00,
                'bill_allocation' => 0.00,
                'establishment_date' => '1995-01-01',
                'capital_stock' => 8000,
                'previous_sales' => 300000,
                'employee_count' => 40,
                'business_description' => '住宅建設業',
                'bank_name' => '東京住宅銀行',
                'branch_name_bank' => '渋谷支店',
                'account_type' => 'current',
                'account_number' => '2345678',
                'account_holder' => '株式会社東京住宅',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            [
                'partner_code' => 'CUST003',
                'partner_name' => '株式会社新宿オフィス',
                'partner_name_print' => '株式会社新宿オフィス',
                'partner_name_kana' => 'カブシキガイシャシンジュクオフィス',
                'partner_type' => 'customer',
                'representative' => '高橋二郎',
                'representative_kana' => 'タカハシジロウ',
                'branch_name' => '本社',
                'postal_code' => '160-0001',
                'address' => '東京都新宿区新宿1-1-1',
                'building_name' => '新宿オフィスビル10F',
                'phone' => '03-5678-9012',
                'fax' => '03-5678-9013',
                'email' => 'info@shinjuku-office.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 100.00,
                'bill_allocation' => 0.00,
                'establishment_date' => '2000-01-01',
                'capital_stock' => 12000,
                'previous_sales' => 400000,
                'employee_count' => 60,
                'business_description' => 'オフィスビル管理・改修業',
                'bank_name' => '新宿銀行',
                'branch_name_bank' => '新宿支店',
                'account_type' => 'current',
                'account_number' => '3456789',
                'account_holder' => '株式会社新宿オフィス',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            [
                'partner_code' => 'CUST004',
                'partner_name' => '株式会社原宿カフェ',
                'partner_name_print' => '株式会社原宿カフェ',
                'partner_name_kana' => 'カブシキガイシャハラジュクカフェ',
                'partner_type' => 'customer',
                'representative' => '伊藤三郎',
                'representative_kana' => 'イトウサブロウ',
                'branch_name' => '本社',
                'postal_code' => '150-0001',
                'address' => '東京都渋谷区神宮前1-1-1',
                'building_name' => '原宿カフェビル2F',
                'phone' => '03-6789-0123',
                'fax' => '03-6789-0124',
                'email' => 'info@harajuku-cafe.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 100.00,
                'bill_allocation' => 0.00,
                'establishment_date' => '2010-01-01',
                'capital_stock' => 3000,
                'previous_sales' => 80000,
                'employee_count' => 15,
                'business_description' => 'カフェ・飲食店経営',
                'bank_name' => '原宿銀行',
                'branch_name_bank' => '原宿支店',
                'account_type' => 'current',
                'account_number' => '4567890',
                'account_holder' => '株式会社原宿カフェ',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            [
                'partner_code' => 'CUST005',
                'partner_name' => '株式会社川越製造',
                'partner_name_print' => '株式会社川越製造',
                'partner_name_kana' => 'カブシキガイシャカワゴエセイゾウ',
                'partner_type' => 'customer',
                'representative' => '渡辺四郎',
                'representative_kana' => 'ワタナベシロウ',
                'branch_name' => '本社',
                'postal_code' => '350-0001',
                'address' => '埼玉県川越市川越1-1-1',
                'building_name' => '川越製造ビル3F',
                'phone' => '049-123-4567',
                'fax' => '049-123-4568',
                'email' => 'info@kawagoe-manufacturing.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 100.00,
                'bill_allocation' => 0.00,
                'establishment_date' => '1988-01-01',
                'capital_stock' => 20000,
                'previous_sales' => 600000,
                'employee_count' => 80,
                'business_description' => '製造業',
                'bank_name' => '川越銀行',
                'branch_name_bank' => '川越支店',
                'account_type' => 'current',
                'account_number' => '5678901',
                'account_holder' => '株式会社川越製造',
                'is_active' => true,
                'created_by' => $user->id,
            ],
            [
                'partner_code' => 'CUST006',
                'partner_name' => '株式会社世田谷マンション',
                'partner_name_print' => '株式会社世田谷マンション',
                'partner_name_kana' => 'カブシキガイシャセタガヤマンション',
                'partner_type' => 'customer',
                'representative' => '中村五郎',
                'representative_kana' => 'ナカムラゴロウ',
                'branch_name' => '本社',
                'postal_code' => '158-0001',
                'address' => '東京都世田谷区世田谷1-1-1',
                'building_name' => '世田谷マンションビル4F',
                'phone' => '03-7890-1234',
                'fax' => '03-7890-1235',
                'email' => 'info@setagaya-mansion.co.jp',
                'is_subcontractor' => false,
                'closing_date' => 99,
                'deposit_terms' => '翌月',
                'deposit_date' => 99,
                'deposit_method' => '振込',
                'cash_allocation' => 100.00,
                'bill_allocation' => 0.00,
                'establishment_date' => '1992-01-01',
                'capital_stock' => 15000,
                'previous_sales' => 350000,
                'employee_count' => 45,
                'business_description' => 'マンション管理・修繕業',
                'bank_name' => '世田谷銀行',
                'branch_name_bank' => '世田谷支店',
                'account_type' => 'current',
                'account_number' => '6789012',
                'account_holder' => '株式会社世田谷マンション',
                'is_active' => true,
                'created_by' => $user->id,
            ],
        ];

        foreach ($partners as $partnerData) {
            Partner::create($partnerData);
        }
    }
}
