<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProjectType;
use App\Models\User;

class ProjectTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 既存のプロジェクトタイプデータをクリア
        ProjectType::truncate();

        // テスト用ユーザーを取得
        $user = User::first();
        if (!$user) {
            $user = User::create([
                'employee_id' => 'TEST001',
                'name' => 'テストユーザー',
                'email' => 'test@example.com',
                'password' => bcrypt('password'),
                'is_active' => true,
            ]);
        }

        // 工事種別データ
        $projectTypes = [
            [
                'type_code' => '6',
                'type_name' => 'F:その他工事',
                'type_symbol' => 'F',
                'description' => 'その他の工事',
                'overhead_rate' => 10.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 10,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '10',
                'type_name' => '土木一式',
                'type_symbol' => 'D',
                'description' => '土木一式工事',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 20,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '20',
                'type_name' => '建築一式（元請）公共',
                'type_symbol' => '',
                'description' => '建築一式工事（元請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 30,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '21',
                'type_name' => '建築一式（元請）民間',
                'type_symbol' => '',
                'description' => '建築一式工事（元請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 40,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '23',
                'type_name' => '建築一式（下請）公共',
                'type_symbol' => '',
                'description' => '建築一式工事（下請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 50,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '24',
                'type_name' => '建築一式（下請）民間',
                'type_symbol' => '',
                'description' => '建築一式工事（下請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 60,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '50',
                'type_name' => 'とび土工（元請）公共',
                'type_symbol' => '',
                'description' => 'とび土工工事（元請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 70,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '51',
                'type_name' => 'とび土工（元請）民間',
                'type_symbol' => '',
                'description' => 'とび土工工事（元請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 80,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '52',
                'type_name' => 'とび土工（下請）公共',
                'type_symbol' => '',
                'description' => 'とび土工工事（下請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 90,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '53',
                'type_name' => 'とび土工（下請）民間',
                'type_symbol' => '',
                'description' => 'とび土工工事（下請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 100,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '170',
                'type_name' => '塗装（元請）公共',
                'type_symbol' => '',
                'description' => '塗装工事（元請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 110,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '171',
                'type_name' => '塗装（元請）民間',
                'type_symbol' => '',
                'description' => '塗装工事（元請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 120,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '172',
                'type_name' => '塗装（下請）公共',
                'type_symbol' => '',
                'description' => '塗装工事（下請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 130,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '173',
                'type_name' => '塗装（下請）民間',
                'type_symbol' => '',
                'description' => '塗装工事（下請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 140,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '180',
                'type_name' => '防水新築（元請）公共',
                'type_symbol' => '',
                'description' => '防水新築工事（元請・公共）',
                'overhead_rate' => 13.50,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 150,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '181',
                'type_name' => '防水新築（元請）民間',
                'type_symbol' => '',
                'description' => '防水新築工事（元請・民間）',
                'overhead_rate' => 13.50,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 160,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '182',
                'type_name' => '防水新築（下請）公共',
                'type_symbol' => '',
                'description' => '防水新築工事（下請・公共）',
                'overhead_rate' => 13.50,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 170,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '183',
                'type_name' => '防水新築（下請）民間',
                'type_symbol' => '',
                'description' => '防水新築工事（下請・民間）',
                'overhead_rate' => 13.50,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 180,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '184',
                'type_name' => '防水（元請）公共',
                'type_symbol' => '',
                'description' => '防水工事（元請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 190,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '185',
                'type_name' => '防水（元請）民間',
                'type_symbol' => '',
                'description' => '防水工事（元請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 200,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '186',
                'type_name' => '防水（下請）公共',
                'type_symbol' => '',
                'description' => '防水工事（下請・公共）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 210,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '187',
                'type_name' => '防水（下請）民間',
                'type_symbol' => '',
                'description' => '防水工事（下請・民間）',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 220,
                'created_by' => $user->id,
            ],
            [
                'type_code' => '290',
                'type_name' => '解体',
                'type_symbol' => '',
                'description' => '解体工事',
                'overhead_rate' => 20.00,
                'cost_expense_rate' => 3.00,
                'material_expense_rate' => 5.00,
                'is_active' => true,
                'sort_order' => 230,
                'created_by' => $user->id,
            ],
        ];

        foreach ($projectTypes as $projectTypeData) {
            ProjectType::create($projectTypeData);
        }
    }
}
